name: 'AOP-test-TS-action manifest'
on: # rebuild any PRs and main branch changes
  workflow_dispatch:
  workflow_call:

jobs:
  read:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    
    steps:
      - name: Run a multi-line script
        run: |
          nwo="actions-on-packages/typescript-action"
          tag="1.4.18"
          host="https://ghcr.io"
          manifest_uri="${host}/v2/${nwo}/manifests/${tag}"
          GHCR_TOKEN=$(echo ${{ secrets.PAT }} | base64)
          curl -X GET "${manifest_uri}" -H "Authorization: Bearer ${GHCR_TOKEN}" -H "Accept: application/vnd.oci.image.manifest.v1+json"
